name: celesteria
description: Phase 0 foundation contracts for the Celesteria cross-platform ACG player.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  libtorrent_flutter: ^1.8.5
  media_kit: ^1.2.6
  media_kit_libs_windows_video: ^1.0.11
  media_kit_video: ^2.0.1
  sqlite3: ^3.3.3
  xml: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
